language: node_js

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

node_js:
  - "10"

script:
  - yarn run test
  - yarn run build

after_success:
  - bash <(curl -s https://codecov.io/bash)